---
- name: Get amazon linux version from /etc/system-release.
  shell: cat /etc/system-release | grep 'Amazon Linux release 2.0'
  changed_when: False
  ignore_errors: True
  register: amzn2

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_distribution != 'Amazon'

- name: Include OS-specific variables (AmazonLinux).
  include_vars: AmazonLinux.yml
  when: ansible_distribution == 'Amazon' and amzn2|failed

- name: Include OS-specific variables (AmazonLinux2).
  include_vars: AmazonLinux2.yml
  when: ansible_distribution == 'Amazon' and amzn2|success

- name: debug
  debug:
    msg: "supervisor_bin_path {{ supervisor_bin_path }}, supervisor_ctl_bin_path {{ supervisor_ctl_bin_path }}"

- name: Ensure Supervisor is installed (specific version).
  pip:
    name: supervisor
    state: present
    version: "{{ supervisor_version }}"
  when: supervisor_version != 'latest'

- name: Ensure Supervisor is installed (latest version).
  pip:
    name: supervisor
    state: present
  when: supervisor_version == 'latest'

- name: Ensure Supervisor log dir exists.
  file:
    path: "{{ supervisor_log_dir }}"
    state: directory
    mode: 0755

- include: config.yml

- include: init-setup.yml
  when: supervisor_started or supervisor_enabled

- name: Ensure Supervisor is started (if configured).
  service:
    name: supervisord
    state: started
  when: supervisor_started

- name: Ensure Supervisor is enabled at boot (if configured).
  service:
    name: supervisord
    enabled: yes
  when: supervisor_enabled
